### PR TITLE
Baf 849/fleet management

### PR DESCRIPTION
**Pull request by MarioIvancik**
Task:
https://youtrack.bringauto.com/issue/BAF-849/Add-Fleet-Management-Integration-Lay.-to-etna

### CODE REVIEW

**Comment by Nothrax** [comment]
scripts/requirements.txt is missing dependencies pydantic and python-dateutil, after installing missing deps I get an error running the fleet init:

```
Traceback (most recent call last):
  File "/home/nothrax/Documents/bringauto/etna/scripts/venv/lib/python3.10/site-packages/urllib3/connection.py", line 198, in _new_conn
    sock = connection.create_connection(
  File "/home/nothrax/Documents/bringauto/etna/scripts/venv/lib/python3.10/site-packages/urllib3/util/connection.py", line 85, in create_connection
    raise err
  File "/home/nothrax/Documents/bringauto/etna/scripts/venv/lib/python3.10/site-packages/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/nothrax/Documents/bringauto/etna/scripts/venv/lib/python3.10/site-packages/urllib3/connectionpool.py", line 793, in urlopen
    response = self._make_request(
  File "/home/nothrax/Documents/bringauto/etna/scripts/venv/lib/python3.10/site-packages/urllib3/connectionpool.py", line 496, in _make_request
    conn.request(
  File "/home/nothrax/Documents/bringauto/etna/scripts/venv/lib/python3.10/site-packages/urllib3/connection.py", line 400, in request
    self.endheaders()
  File "/usr/lib/python3.10/http/client.py", line 1278, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1038, in _send_output
    self.send(msg)
  File "/usr/lib/python3.10/http/client.py", line 976, in send
    self.connect()
  File "/home/nothrax/Documents/bringauto/etna/scripts/venv/lib/python3.10/site-packages/urllib3/connection.py", line 238, in connect
    self.sock = self._new_conn()
  File "/home/nothrax/Documents/bringauto/etna/scripts/venv/lib/python3.10/site-packages/urllib3/connection.py", line 213, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7fa0ca68cac0>: Failed to establish a new connection: [Errno 111] Connection refused

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/nothrax/Documents/bringauto/etna/scripts/fleet-init/main.py", line 100, in <module>
    main()
  File "/home/nothrax/Documents/bringauto/etna/scripts/fleet-init/main.py", line 86, in main
    delete_all(api_client)
  File "/home/nothrax/Documents/bringauto/etna/scripts/fleet-init/fleet/query/utils.py", line 12, in delete_all
    orders = order_api.get_orders()
  File "/home/nothrax/Documents/bringauto/etna/scripts/venv/lib/python3.10/site-packages/pydantic/validate_call_decorator.py", line 59, in wrapper_function
    return validate_call_wrapper(*args, **kwargs)
  File "/home/nothrax/Documents/bringauto/etna/scripts/venv/lib/python3.10/site-packages/pydantic/_internal/_validate_call.py", line 81, in __call__
    res = self.__pydantic_validator__.validate_python(pydantic_core.ArgsKwargs(args, kwargs))
  File "/home/nothrax/Documents/bringauto/etna/scripts/venv/lib/python3.10/site-packages/fleet_management_http_client_python/api/order_api.py", line 1233, in get_orders
    response_data = self.api_client.call_api(
  File "/home/nothrax/Documents/bringauto/etna/scripts/venv/lib/python3.10/site-packages/fleet_management_http_client_python/api_client.py", line 270, in call_api
    response_data = self.rest_client.request(
  File "/home/nothrax/Documents/bringauto/etna/scripts/venv/lib/python3.10/site-packages/fleet_management_http_client_python/rest.py", line 244, in request
    r = self.pool_manager.request(
  File "/home/nothrax/Documents/bringauto/etna/scripts/venv/lib/python3.10/site-packages/urllib3/_request_methods.py", line 136, in request
    return self.request_encode_url(
  File "/home/nothrax/Documents/bringauto/etna/scripts/venv/lib/python3.10/site-packages/urllib3/_request_methods.py", line 183, in request_encode_url
    return self.urlopen(method, url, **extra_kw)
  File "/home/nothrax/Documents/bringauto/etna/scripts/venv/lib/python3.10/site-packages/urllib3/poolmanager.py", line 444, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/home/nothrax/Documents/bringauto/etna/scripts/venv/lib/python3.10/site-packages/urllib3/connectionpool.py", line 877, in urlopen
    return self.urlopen(
  File "/home/nothrax/Documents/bringauto/etna/scripts/venv/lib/python3.10/site-packages/urllib3/connectionpool.py", line 877, in urlopen
    return self.urlopen(
  File "/home/nothrax/Documents/bringauto/etna/scripts/venv/lib/python3.10/site-packages/urllib3/connectionpool.py", line 877, in urlopen
    return self.urlopen(
  File "/home/nothrax/Documents/bringauto/etna/scripts/venv/lib/python3.10/site-packages/urllib3/connectionpool.py", line 847, in urlopen
    retries = retries.increment(
  File "/home/nothrax/Documents/bringauto/etna/scripts/venv/lib/python3.10/site-packages/urllib3/util/retry.py", line 515, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=8081): Max retries exceeded with url: /v2/management/order?api_key=ManagementStaticAccessKey (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa0ca68cac0>: Failed to establish a new connection: [Errno 111] Connection refused'))
```

**Comment by Nothrax** [comment]
while running etna with profile "all" I get an error 024-05-18 07:27:52.358 UTC [42] FATAL:  database "management_api" does not exist and  2024-05-18 07:27:53.298 UTC [43] FATAL:  database "protocol_api" does not exist

**Comment by Nothrax** [comment]
VVU container does not work: Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "/virtual-vehicle-utility/bin/virtual-vehicle-utility ": stat /virtual-vehicle-utility/bin/virtual-vehicle-utility : no such file or directory: unknown

**Comment by Nothrax** [comment]
When I was fixed all issues with file permissions and was able to start profile "all" the virtual_vehicle clearly started to communicate with http api:
```
http-api-1                 | 2024-05-18 08:40:24,153 -- No commands available before timeout (Company='bringauto', car='virtual_vehicle').
http-api-1                 | 2024-05-18 08:40:24,153 -- 172.18.0.5 - - [18/May/2024 08:40:24] "GET /v2/protocol/command/bringauto/virtual_vehicle?api_key=ProtocolStaticAccessKey&since=2&wait=true HTTP/1.1" 404 -
http-api-1                 | 2024-05-18 08:40:24,153 -- No commands available before timeout (Company='bringauto', car='virtual_vehicle').
http-api-1                 | 2024-05-18 08:40:24,154 -- 172.18.0.5 - - [18/May/2024 08:40:24] "GET /v2/protocol/command/bringauto/virtual_vehicle?api_key=ProtocolStaticAccessKey&since=2&wait=true HTTP/1.1" 404 -
```
But when I followed the readme, used swagger and tried to get all cars I got an empty response: [] and http api l;ogged:
```
http-api-1                 | 2024-05-18 08:40:22,307 -- No cars were found. Returning empty list.
http-api-1                 | 2024-05-18 08:40:22,308 -- 172.18.0.7 - - [18/May/2024 08:40:22] "GET /v2/protocol/cars?wait=true&since=1&api_key=ProtocolStaticAccessKey HTTP/1.1" 200 -
http-api-1                 | 2024-05-18 08:40:22,310 -- Found 0 available cars for 0 companies.
http-api-1                 | 2024-05-18 08:40:22,310 -- 172.18.0.7 - - [18/May/2024 08:40:22] "GET /v2/protocol/cars?wait=false&since=0&api_key=ProtocolStaticAccessKey HTTP/1.1" 200 -
http-api-1                 | 2024-05-18 08:40:22,455 -- Found 0 available cars for 0 companies.
http-api-1                 | 2024-05-18 08:40:22,455 -- 172.18.0.1 - - [18/May/2024 08:40:22] "GET /v2/protocol/cars?wait=false&since=0&api_key=ProtocolStaticAccessKey HTTP/1.1" 200 -
```
Is there more steps to be able to obtain data from http api? if yes why is it not in readme?

**Comment by Nothrax** [comment]
Expectation: I have machine with docker compose, I download this repo, update submodules, run profile "all" and I can see data in http and management api, before that, this cannot be merged.

**Review by Melky-Phoe — APPROVED** [review]

**Pull request merged**
